version: '3'

services:
  baota:
    image: zhgqthomas/ssrpanel-baota:v1
    container_name: baota
    ports:
      - "80:80"
      - "888:888"
      - "8888:8888"
      - "443:443"
      - "20:20"
      - "21:21"
      - "10000-15000:10000-15000"
    command: sh /start.sh