version: '3'

services:
  baota:
    image: lnmp-baota:v1
    container_name: lnmp-baota
    ports:
      - "80:80"
      - "888:888"
      - "8888:8888"
      - "443:443"
      - "20:20"
      - "21:21"
      - "3306:3306"
    volumes:
      - ./SSRPanel:/www/wwwroot/ssrpanel
    command: bash /start.sh